var TUG=TUG||{};TUG.mBackground="#000000";TUG.mCurrentFrame=0;TUG.mFontBoldV=.25;TUG.mFontShadow=.25;TUG.mFontSize=8;TUG.mFontType="sans-serif";TUG.mFPS=60;TUG.mSmooth=0;TUG.mKey=new Uint8Array(256);TUG.onKeyDown=function(a){};TUG.onPaint=function(a,b,c){};TUG.onTimer=function(){};TUG.BG={};TUG.GR={};TUG.SP={mScreen:1};TUG.TX={};
TUG.PAD={mCode:[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,-1,-1,5,6,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,-1,-1,-1,-1,2,0,3,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,2,8,6,3,11,-1,-1,2,6,1,0,3,10,9,5,4,-1,10,1,9,7,7,0,5,8,4,-1,-1,-1,-1,-1,6,-1,1,-1,2,-1,3,-1,0,-1,9,7,-1,8,5,10,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,11,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],mKey:new Uint8Array(12)};TUG.Collision=function(a,b,c,d,e,f,g,h){a=TUG.Distance(a,c>>1,e,g>>1);b=TUG.Distance(b,d>>1,f,h>>1);return 0<=a||0<=b?0:a<b?1:2};
TUG.SP.Collision=function(a,b){return TUG.Collision(a.mX,a.mY,a.mWidth,a.mHeight,b.mX,b.mY,b.mWidth,b.mHeight)};TUG.Distance=function(a,b,c,d){return Math.abs(a-c)-b-d};TUG.LoadImage=function(a,b){var c=a.length,d={};d.Result=Array(c);d.Completed=0;for(var e=d.AllComplete=0;e<c;e++){var f=new Image;f.src=a[e];d.Result[e]=f;d.Result[e].onload=function(){++d.Completed==c&&(d.AllComplete=1);b&&b(d)}}return d};TUG.Rnd=function(a){return Math.floor(Math.random()*a)};
TUG.Sign=function(a){return 0==a?0:0>a?-1:1};TUG.ZENKAKU_INT="\uff10\uff11\uff12\uff13\uff14\uff15\uff16\uff17\uff18\uff19".split("");TUG.DrawTile=function(a,b,c,d,e,f,g,h){if(h){a.save();var k=1-((h&1)<<1),l=1-(h&2);a.transform(k,0,0,l,f*(1-k)>>1,g*(1-l)>>1);d*=k;e*=l}k=Math.ceil(b.width/f);a.drawImage(b,c%k*f,Math.floor(c/k)*g,f,g,d,e,f,g);h&&a.restore()};
TUG.ToZenkakuInt=function(a,b,c){var d="";c||(c="\u3000");var e=0;0>a&&(a=-a,e=1);do if(d=TUG.ZENKAKU_INT[a%10]+d,a=Math.floor(a/10),b&&0>=--b)return d;while(a);for(b&&e&&b--;b&&b--;)d=c+d;e&&(d="\uff0d"+d);return d};TUG.createCanvas=function(a,b){var c=document.createElement("canvas");c.width=a;c.height=b;return c};
TUG.createTile=function(a,b,c){a.mWidth=b?b:TUG.BG.mWidth;a.mHeight=c?c:TUG.BG.mHeight;a.column=function(){return Math.ceil(this.width/this.mWidth)};a.draw=function(a,b,c,g,h){TUG.DrawTile(a,this,b,c,g,this.mWidth,this.mHeight,h)};a.length=function(){return this.column()*this.row()};a.row=function(){return Math.ceil(this.height/this.mHeight)};return a};
TUG.init=function(a,b,c,d,e,f,g){b||(b=240);c||(c=180);d||(d=16);e||(e=16);f||(f=32);g||(g=32);TUG.mID=a;TUG.mWidth=b;TUG.mHeight=c;TUG.PAD.init();TUG.TX.init();TUG.GR.init(b,c);TUG.BG.init(d,e,f,g);TUG.SP.init();TUG.wmSize();window.addEventListener("resize",function(){TUG.wmSize()});requestAnimationFrame(TUG.wmTimer)};
TUG.wmSize=function(){var a=TUG.mMain=document.getElementById(TUG.mID);TUG.mMC=a.getContext("2d");a.style.position="absolute";window.innerWidth/TUG.mWidth<window.innerHeight/TUG.mHeight?(a.width=window.innerWidth,a.height=window.innerWidth*TUG.mHeight/TUG.mWidth,a.style.left="0px"):(a.width=window.innerHeight*TUG.mWidth/TUG.mHeight,a.height=window.innerHeight,a.style.left=Math.floor((window.innerWidth-a.width)/2)+"px");TUG.mScale=Math.min(a.width/TUG.mWidth,a.height/TUG.mHeight);TUG.TX.mCanvas.width=
a.width;TUG.TX.mCanvas.height=a.height;TUG.TX.mG=TUG.TX.mCanvas.getContext("2d");TUG.TX.mG.font=TUG.mFontSize*TUG.mScale+"px "+TUG.mFontType;TUG.TX.mG.textBaseline="top"};
TUG.wmPaint=function(){TUG.mMC.imageSmoothingEnabled=TUG.mMC.msImageSmoothingEnabled=TUG.mSmooth;TUG.GR.clear();TUG.TX.clear();TUG.onPaint(TUG.GR.mG[0],TUG.GR.mG[1],TUG.TX.mG);TUG.SP.draw();TUG.BG.draw();TUG.GR.draw();TUG.TX.draw();TUG.mMC.drawImage(TUG.GR.mCanvas[0],0,0,TUG.mWidth,TUG.mHeight,0,0,TUG.mMain.width,TUG.mMain.height);TUG.mMC.drawImage(TUG.TX.mCanvas,0,0)};
TUG.wmTimer=function(){TUG.mCurrentStart||(TUG.mCurrentStart=performance.now());for(var a=Math.floor((performance.now()-TUG.mCurrentStart)*TUG.mFPS/1E3)-TUG.mCurrentFrame;a--;){TUG.onTimer();TUG.mCurrentFrame++;for(var b=TUG.mKey.length-1;0<=b;b--)0<TUG.mKey[b]&255>TUG.mKey[b]&&TUG.mKey[b]++;for(b=TUG.PAD.mKey.length-1;0<=b;b--)0<TUG.PAD.mKey[b]&255>TUG.PAD.mKey[b]&&TUG.PAD.mKey[b]++;0==a&&TUG.wmPaint()}requestAnimationFrame(TUG.wmTimer)};
window.onkeydown=function(a){a=a.keyCode;if(0==TUG.mKey[a]){TUG.mKey[a]=1;var b=TUG.PAD.mCode[a];0<=b&&(TUG.PAD.mKey[b]=1);TUG.onKeyDown(a)}};window.onkeyup=function(a){a=a.keyCode;TUG.mKey[a]=0;a=TUG.PAD.mCode[a];0<=a&&(TUG.PAD.mKey[a]=0)};TUG.BG.clearAtr=function(a){for(var b=0;b<TUG.BG.mRow;b++)for(var c=0;c<TUG.BG.mColumn;c++)TUG.BG.setAtr(c,b,a)};
TUG.BG.draw=function(){for(var a=TUG.BG.mY,b=0;b<TUG.mHeight;){for(;a>=TUG.BG.mCanvas.height;)a-=TUG.BG.mCanvas.height;for(;0>a;)a+=TUG.BG.mCanvas.height;for(var c=Math.min(TUG.mHeight-b,TUG.BG.mCanvas.height-a),d=TUG.BG.mX,e=0;e<TUG.mWidth;){for(;d>=TUG.BG.mCanvas.width;)d-=TUG.BG.mCanvas.width;for(;0>d;)d+=TUG.BG.mCanvas.width;var f=Math.min(TUG.mWidth-e,TUG.BG.mCanvas.width-d);TUG.GR.mG[0].drawImage(TUG.BG.mCanvas,d,a,f,c,e,b,f,c);e+=f;d+=f}b+=c;a+=c}};
TUG.BG.drawTile=function(a,b){var c=a*TUG.BG.mWidth,d=b*TUG.BG.mHeight,e=TUG.BG.getIndex(a,b),f=TUG.BG.mAtrb[e];f&1?TUG.BG.mG.clearRect(c,d,TUG.BG.mWidth,TUG.BG.mHeight):TUG.BG.mTile.draw(TUG.BG.mG,TUG.BG.mData[e],c,d,f>>1)};TUG.BG.getAtr=function(a,b){return TUG.BG.mAtrb[TUG.BG.getIndex(a,b)]};TUG.BG.getIndex=function(a,b){return b*TUG.BG.mColumn+a};TUG.BG.getVal=function(a,b){return TUG.BG.mData[TUG.BG.getIndex(a,b)]};
TUG.BG.init=function(a,b,c,d){TUG.BG.mWidth=a;TUG.BG.mHeight=b;TUG.BG.mColumn=c;TUG.BG.mRow=d;TUG.BG.mX=0;TUG.BG.mY=0;TUG.BG.mData=new Uint16Array(c*d);TUG.BG.mAtrb=new Uint8Array(c*d);TUG.BG.mCanvas=TUG.createCanvas(a*c,b*d);TUG.BG.mG=TUG.BG.mCanvas.getContext("2d")};TUG.BG.setImage=function(a){TUG.BG.setTile(TUG.createTile(a,TUG.BG.mWidth,TUG.BG.mHeight))};TUG.BG.setTile=function(a){TUG.BG.mTile=a;for(a=0;a<TUG.BG.mRow;a++)for(var b=0;b<TUG.BG.mColumn;b++)TUG.BG.setValMain(b,a,TUG.BG.getVal(b,a))};
TUG.BG.setAtr=function(a,b,c){TUG.BG.getAtr(a,b)!=c&&TUG.BG.mTile&&TUG.BG.setAtrMain(a,b,c)};TUG.BG.setAtrMain=function(a,b,c){TUG.BG.mAtrb[TUG.BG.getIndex(a,b)]=c;TUG.BG.drawTile(a,b)};TUG.BG.setVal=function(a,b,c){TUG.BG.getVal(a,b)!=c&&TUG.BG.mTile&&TUG.BG.setValMain(a,b,c)};TUG.BG.setValMain=function(a,b,c){TUG.BG.mData[TUG.BG.getIndex(a,b)]=c;TUG.BG.drawTile(a,b)};
TUG.BG.setValAtrMain=function(a,b,c,d){TUG.BG.mData[TUG.BG.getIndex(a,b)]=c;TUG.BG.mAtrb[TUG.BG.getIndex(a,b)]=d;TUG.BG.drawTile(a,b)};TUG.GR.clear=function(){TUG.GR.mG[0].fillStyle=TUG.mBackground;TUG.GR.mG[0].fillRect(0,0,TUG.GR.mCanvas[0].width,TUG.GR.mCanvas[0].height);TUG.GR.mG[1].clearRect(0,0,TUG.GR.mCanvas[1].width,TUG.GR.mCanvas[1].height)};TUG.GR.draw=function(){TUG.GR.mG[0].drawImage(TUG.GR.mCanvas[1],0,0)};
TUG.GR.init=function(a,b){TUG.GR.mCanvas=Array(2);TUG.GR.mCanvas[0]=TUG.createCanvas(a,b);TUG.GR.mCanvas[1]=TUG.createCanvas(a,b);TUG.GR.mG=Array(2);TUG.GR.mG[0]=TUG.GR.mCanvas[0].getContext("2d");TUG.GR.mG[1]=TUG.GR.mCanvas[1].getContext("2d")};
TUG.PAD.init=function(){Object.defineProperty(TUG.PAD,"Up",{get:function(){return this.mKey[0]},configurable:!0});Object.defineProperty(TUG.PAD,"Down",{get:function(){return this.mKey[1]},configurable:!0});Object.defineProperty(TUG.PAD,"Left",{get:function(){return this.mKey[2]},configurable:!0});Object.defineProperty(TUG.PAD,"Right",{get:function(){return this.mKey[3]},configurable:!0});Object.defineProperty(TUG.PAD,"A",{get:function(){return this.mKey[4]},configurable:!0});Object.defineProperty(TUG.PAD,
"B",{get:function(){return this.mKey[5]},configurable:!0});Object.defineProperty(TUG.PAD,"C",{get:function(){return this.mKey[6]},configurable:!0});Object.defineProperty(TUG.PAD,"D",{get:function(){return this.mKey[7]},configurable:!0});Object.defineProperty(TUG.PAD,"E",{get:function(){return this.mKey[8]},configurable:!0});Object.defineProperty(TUG.PAD,"F",{get:function(){return this.mKey[9]},configurable:!0});Object.defineProperty(TUG.PAD,"G",{get:function(){return this.mKey[10]},configurable:!0});
Object.defineProperty(TUG.PAD,"H",{get:function(){return this.mKey[11]},configurable:!0})};TUG.SP.add=function(a){TUG.SP.mData.push(a)};
TUG.SP.create=function(a,b){var c={};c.mTile=a;c.mX=0;c.mY=0;c.mWidth=a.mWidth;c.mHeight=a.mHeight;c.mMeshHeight=a.mHeight/TUG.BG.mHeight;c.mAtr=0;c.mEnable=1;c.mIdx=b?b:0;c.mG=TUG.GR.mG[TUG.SP.mScreen];c.collision=function(a){return TUG.SP.Collision(this,a)};c.draw=function(){c.mTile.draw(this.mG,this.mIdx,this.mX-(c.mTile.mWidth>>1),this.mY-(c.mTile.mHeight>>1),this.mAtr)};c.setScreen=function(a){c.mG=TUG.GR.mG[a]};return c};
TUG.SP.draw=function(){for(var a=TUG.SP.mData.length-1;0<=a;a--){var b=TUG.SP.mData[a];b.mEnable&&b.draw()}};TUG.SP.erase=function(a){for(var b=TUG.SP.mData.length-1;0<=b;b--)if(TUG.SP.mData[b]==a){TUG.SP.mData.splice(b,1);break}};TUG.SP.init=function(){TUG.SP.mData=[]};TUG.TX.add=function(a){TUG.TX.mData.push(a)};TUG.TX.clear=function(){TUG.TX.mG.clearRect(0,0,TUG.TX.mCanvas.width,TUG.TX.mCanvas.height)};
TUG.TX.createIntZen=function(a,b,c,d,e,f){var g={};g.mVal=a;g.mX=b;g.mY=c;g.mStyle=d;g.mKeta=e;g.mChr=f;g.draw=function(){TUG.TX.fillTextR(TUG.ToZenkakuInt(this.mVal,this.mKeta,this.mChr),this.mX,this.mY,this.mStyle)};return g};TUG.TX.createStr=function(a,b,c,d){var e={};e.mStr=a;e.mX=b;e.mY=c;e.mStyle=d;e.draw=function(){TUG.TX.fillText(this.mStr,this.mX,this.mY,this.mStyle)};return e};TUG.TX.draw=function(){for(var a=TUG.TX.mData.length-1;0<=a;a--)TUG.TX.mData[a].draw()};
TUG.TX.fillRect=function(a,b,c,d,e){e&&(TUG.TX.mG.fillStyle=e);TUG.TX.mG.fillRect(a*TUG.mScale,b*TUG.mScale,c*TUG.mScale,d*TUG.mScale)};TUG.TX.fillText=function(a,b,c,d){TUG.TX.mShadow&&TUG.TX.fillTextMain(a,b+TUG.mFontShadow*TUG.mScale,c+TUG.mFontShadow*TUG.mScale,TUG.TX.mShadow);TUG.TX.fillTextMain(a,b,c,d)};
TUG.TX.fillTextMain=function(a,b,c,d){d&&(TUG.TX.mG.fillStyle=d);TUG.TX.mG.fillText(a,b*TUG.mScale,c*TUG.mScale);TUG.mFontBoldV&&TUG.TX.mG.fillText(a,b*TUG.mScale,c*TUG.mScale+TUG.mFontBoldV*TUG.mScale)};TUG.TX.fillTextR=function(a,b,c,d){TUG.TX.mG.textAlign="right";TUG.TX.fillText(a,b,c,d);TUG.TX.mG.textAlign="start"};TUG.TX.init=function(){TUG.TX.mCanvas=document.createElement("canvas");TUG.TX.mData=[]};
TUG.TX.strokeRect=function(a,b,c,d,e,f){e&&(TUG.TX.mG.strokeStyle=e);f&&(TUG.TX.mG.lineWidth=f*TUG.mScale);TUG.TX.mG.strokeRect(a*TUG.mScale,b*TUG.mScale,c*TUG.mScale,d*TUG.mScale)};